Added methods to get files based on the path when Drive mounted in Jupyter Lab
HumanBrainProject/ebrains-drive pull request #8
Opened 2021-06-03 19:39 UTC by apdavison

also implemented method to get sharing link

2021-11-17 12:10 UTC, Cracky5457 commented
hello Andrew, thanks for implementing that.

Sorry for the delay, I'm reviewing it right now and I will try to release it in the week.

2021-11-17 17:01 UTC, Cracky5457 requested changes

2021-11-17 17:01 UTC, Cracky5457 commented on ebrains_drive/file.py
> +            collab_name = local_path.split("/")[5]
I will replace it by a simple `local_path.replace(group_dir,"")` so we won't have issue if the amount of `/` is different if there is a `/` in the collab title.

2021-11-17 17:03 UTC, Cracky5457 commented
Lab is actually not available to test it due to the infrastructure migration, I will apply the changes suggested in my review and push a new branch ( I can't commit on your PR it's in your own repo ) and release de .dev version to test it on the lab

2021-11-18 16:49 UTC, appukuttan-shailesh commented
@Cracky5457 : would it be possible to review this and make a new release (0.2.1 ?) of `ebrains-drive` before this weekend?
We have the CodeJam event next week, and we are planning a small demo of this library. It would be nice to work with the latest release, and to be able to test it prior to the demo.

2021-11-22 11:12 UTC, Cracky5457 commented
Merged and fixed on master directly

2021-11-22 11:12 UTC, closed without merging